# Generated by Django 6.0.4 on 2026-04-21 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_prioridade'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='prioridade',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='titulo',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
    ]
