# Generated by Django 6.0.4 on 2026-04-21 00:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_remove_tarefa_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_entrega',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Não Urgente')], default='NAO_URGENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
